# job to install packages to prod path sandboxes (after sit1) and production
name: Deployment
on:
  workflow_dispatch:
    inputs: 
      environment:
        description: 'Enviornment to install'
        required: true
        default: 'sandboxes'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      # configure aws variables
      - name: Configure container registry
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_SALESFORCEDX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_SALESFORCEDX_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ORG_SALESFORCEDX_AWS_REGION }}
      # login to container registry
      - name: Login to container registry
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # install package to the environment
      - name: Deployment
        id: install_ci
        uses: ./workflow/run-container-deploy # Uses an action in the specified directory
        env:
          SSH_KEY: ${{ secrets.ORG_SALESFORCEDX_USER_SSH_KEY }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          DEV_HUB_URL: ${{ secrets.ORG_SALESFORCEDX_PROD_URL }}
          ENV_UAT2_URL: ${{ secrets.ORG_SALESFORCEDX_UAT2_URL }}
          ENV_TRAINING_URL: ${{ secrets.ORG_SALESFORCEDX_TRAINING_URL }}
          SCRIPTS_PATH: /operation/workspace
          BRANCH: ${{ github.ref }}
          IMAGE_NAME: sfdx-config:latest
        # pass input parameter
        with:
          # operation to perform
          operation: deployment
          # url to pull image
          imageurl: ${{ steps.login-aws-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
          # workspace path
          workspace: $GITHUB_WORKSPACE